version: '3'

services:
  db:
    image: mysql
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_passsword


  bot:
    image: bot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db

volumes:
  mysql:
